# Generated by Django 3.1.1 on 2021-01-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('inclination', models.DecimalField(decimal_places=3, max_digits=6)),
                ('radius', models.DecimalField(decimal_places=1, max_digits=20)),
                ('mass', models.CharField(max_length=100)),
                ('average_orbital_speed', models.DecimalField(decimal_places=3, max_digits=10)),
                ('orbital_period', models.DecimalField(decimal_places=9, max_digits=20)),
            ],
        ),
    ]
